transform: work around renamed return type after merging LLVM modules
tinygo-org/tinygo pull request #1898
Opened 2021-05-20 18:27 UTC by aykevl

This fix is very similar to
https://github.com/tinygo-org/tinygo/pull/1768, but now for the return
type. It fixes the issue in
https://github.com/tinygo-org/tinygo/issues/1887.

Like #1768, I'm not sure how to test this as it is very specific to
certain renames that LLVM does and that don't seem very reproducable.

2021-06-25 14:17 UTC, deadprogram commented
I do not understand the implications of this change sufficiently, even though it is just one line. Are we sure this is safe?

2021-10-21 20:05 UTC, aykevl commented
Yes, I'm pretty sure it is :)
Also, this continues to be a problem (see https://github.com/tinygo-org/tinygo/issues/1887#issuecomment-894928366 and https://github.com/tinygo-org/tinygo/issues/2197).

2021-10-27 13:59 UTC, niaow requested changes
I think this resolves the problem with this specific bug, although it looks like we may have another similar bug in another pass. Can we add a test to the transform first (put something into the `testdata/interface.ll`)?

2021-10-27 23:08 UTC, niaow approved these changes
Nevermind, I actually see what you mean now. Sorry. LGTM.

2021-10-28 07:20 UTC, deadprogram commented
Thanks @aykevl for the work-around and @niaow for reviewing. Now merging.

2021-10-28 07:20 UTC, merged