Add support for the stm32f469-discovery board
tinygo-org/tinygo pull request #2434
Opened 2021-12-28 18:59 UTC by eliasnaur

2021-12-29 10:02 UTC, deadprogram commented
Hello @eliasnaur looks like you need to rebase this branch against `dev` please.

2021-12-29 21:09 UTC, eliasnaur commented
I did that already and GitHubs says there are no conflicts. Did I miss anything?

2021-12-29 21:45 UTC, kenbell commented
@eliasnaur - i want to go through these changes in a bit of detail which may take a day or two.  It's really great you've unified the code - and there's some patterns here that we can re-use in other STM32 families.

I notice some constants have changed, e.g. now:
```go
	if config.Frequency > 10000 {
		min = 4 // fast mode (Fm)
	}
```
the F407 implementation was 100k, not 10k - 100K intuitively seemed like it was the correct value, but i need to double-check the documentation.
```go
	if config.Frequency > 100000 {
		min = 4 // fast mode (Fm)
	}
```

I've spun up your branch on the stm32f407 disco, and basic blink and UART looks great.  Have you had the change to test I2C or SPI?

In the meantime, would be great to update `README.md` to add the new target and also to add the target to the `smoketests` command in the `Makefile`.

2021-12-29 23:12 UTC, eliasnaur commented
> @eliasnaur - i want to go through these changes in a bit of detail which may take a day or two. It's really great you've unified the code - and there's some patterns here that we can re-use in other STM32 families.
> 

Thanks! I suspect runtime_stm32f405.go can be replaced as well, but I'm not proficient enough to make that call, and don't have a 405 board to test on.

> I notice some constants have changed, e.g. now:
> 
> ```go
> 	if config.Frequency > 10000 {
> 		min = 4 // fast mode (Fm)
> 	}
> ```
> 
> the F407 implementation was 100k, not 10k - 100K intuitively seemed like it was the correct value, but i need to double-check the documentation.
> 
> ```go
> 	if config.Frequency > 100000 {
> 		min = 4 // fast mode (Fm)
> 	}
> ```
> 

Indeed, I mentioned the frequency limit in one of the commit, but should have made that change clearer. In particular because I don't know what the correct limit is (or are, if they vary per board).

> I've spun up your branch on the stm32f407 disco, and basic blink and UART looks great. Have you had the change to test I2C or SPI?
>

I don't have a 407, so I assume you mean testing 469. I don't have any hardware other than the 469 board; can I test I2C and SPI without?
 
> In the meantime, would be great to update `README.md` to add the new target and also to add the target to the `smoketests` command in the `Makefile`.

Done.

2021-12-30 17:00 UTC, kenbell requested changes
Requesting a few minor changes (see inline comments).  The I2C comparison should be 100K, and just a couple over minor housekeeping bits and pieces.

I've tested I2C and GPIO on stm32f407-disco and works great.  My testing of SPI wasn't successful - but it was equally broken before this change, so needs separate investigation / PR.

Overall - this looks great.  With a couple small changes, I think this is good to go.

2021-12-30 17:00 UTC, kenbell commented on src/machine/machine_stm32f4.go
> +	if config.Frequency > 10000 {
Per RM0386, §29.3 and RM0090, §27.3 standard mode is up-to 100KHz, fast mode up to 400KHz.  In fast-mode, minimum is 4MHz peripheral input clock.  It looks like the original F405 code was incorrect.   Can you change this to 100K.

2021-12-30 17:00 UTC, kenbell commented on README.md
> +* [ST Micro STM32F469 "Discovery"](https://www.st.com/content/st_com/en/products/evaluation-tools/product-evaluation-tools/mcu-mpu-eval-tools/stm32-mcu-mpu-eval-tools/stm32-discovery-kits/32f469idisc
Can you also increment count by 1 at the top of the list

2021-12-30 17:00 UTC, kenbell commented on Makefile
> +	$(TINYGO) build -size short -o test.hex -target=stm32f469disco      examples/blinky2
It's probably fine just to have a single blinky built as part of the smoketest, can remove blinky2 IMO

2021-12-30 21:59 UTC, kenbell commented
I've confirmed SPI is also working great on stm32f407 - earlier problems were with my setup.

2021-12-30 23:01 UTC, eliasnaur commented on src/machine/machine_stm32f4.go
> +	if config.Frequency > 10000 {
Thanks for checking up on this!

2021-12-30 23:02 UTC, eliasnaur commented
Thank you for your thorough review. All requested changes should be done now.

2021-12-31 10:25 UTC, kenbell approved these changes

2021-12-31 10:30 UTC, kenbell commented
@eliasnaur - thanks for the great contribution. Merging now.

2021-12-31 10:30 UTC, merged