Challenger rp2040
tinygo-org/tinygo pull request #2952
Opened 2022-07-01 16:09 UTC by kenbell

This board is a feather-rp2040 derivative, but does not have the UART on conventional pins, so move the UART definitions to per-board.  I don't have all boards, but where the docs/schematic suggest only a single UART is exposed, i've removed the definitions related to the other UART (typically UART0 is exposed, whereas UART1 may not be).

There's also a change to git ignore a file created by smoketest

2022-07-01 16:10 UTC, kenbell commented
I'm working on a separate change to add support for the on-board LoRa chip to the drivers package.

2022-07-02 11:30 UTC, sago35 commented
![image](https://user-images.githubusercontent.com/9251039/176998919-5bffd63d-2283-41a7-adb1-6d4d34e67c7c.png)

https://ilabs.se/product/challenger-rp2040-lora/

2022-07-02 11:32 UTC, sago35 commented
@kenbell 
Could you add VID, PID, etc.
USB for rp2040 will be available soon.

ref : #2936

https://github.com/earlephilhower/arduino-pico/blob/master/boards.txt

```
# -----------------------------------
# iLabs Challenger 2040 LoRa
# -----------------------------------
challenger_2040_lora.vid.0=0x2e8a
challenger_2040_lora.pid.0=0x1023
challenger_2040_lora.build.vid=0x2e8a
challenger_2040_lora.build.pid=0x1023
challenger_2040_lora.build.usb_manufacturer="iLabs"
challenger_2040_lora.build.usb_product="Challenger 2040 LoRa"
```

2022-07-02 14:14 UTC, kenbell commented
@sago35 - thanks for taking a look. I have pushed a new change with the USB info.

2022-07-04 11:52 UTC, sago35 requested changes
There is a typo.

2022-07-04 11:52 UTC, sago35 commented on src/machine/board_feather_rp2040.go
> +	UART1  = &_UART0
`&_UART1` ?

2022-07-04 11:52 UTC, sago35 commented on src/machine/board_challenger_rp2040.go
> +	UART1  = &_UART0
`&_UART1` ?

2022-07-04 11:52 UTC, sago35 commented on src/machine/board_pico.go
> +	UART1  = &_UART0
`&_UART1` ?

2022-07-04 14:08 UTC, kenbell commented
@sago35 thanks for spotting those typos.  I've updated the PR

2022-07-05 03:57 UTC, sago35 approved these changes
LGTM

2022-07-07 15:42 UTC, kenbell commented
It took a couple go-arounds to merge the xaio-rp2040 changes, but looks good now.

@deadprogram I think this is ready to merge to dev

2022-07-08 08:35 UTC, deadprogram commented
Please rebase one more time against `dev`, please.

2022-07-08 10:31 UTC, kenbell commented
thanks @deadprogram - rebased

2022-07-08 11:01 UTC, deadprogram commented
Thanks @kenbell now merging.

2022-07-08 11:01 UTC, merged