CGo: Add CBytes implementation
tinygo-org/tinygo pull request #3318
Opened 2022-11-29 01:58 UTC by waj334

Adds the CBytes implementation from mainstream Go. Also corrects a random typo in a comment.

2022-11-29 15:34 UTC, aykevl requested changes

2022-11-29 15:34 UTC, aykevl commented on src/runtime/string.go
> +	}{p, len(b), len(b)}
TinyGo uses `uintptr` instead of `int` here. It's a small difference necessary to support AVR.

2022-11-29 15:34 UTC, aykevl commented on testdata/cgo/main.go
> +	/*println("C.CBytes(nil):", C.CBytes(nil))*/
You can test whether the bytes are there after the call, and/or whether it roundtrips with `C.GoBytes`.

2022-12-12 19:45 UTC, aykevl reviewed
Can you add a test like the following, that tests whether bytes correctly roundtrip through `C.GoBytes`/`C.CBytes`?

```go
p := C.CBytes([]byte("hello\0"))
println(`rountrip CBytes:`, C.GoString(p))
C.free(p)
```

2022-12-12 19:45 UTC, aykevl commented on src/runtime/string.go
> +	s := *(*[]byte)(unsafe.Pointer(&sliceHeader))
Sorry I realized this only now but there is a much cleaner way to do this:

```suggestion
    s := unsafe.Slice(p, len(b))
```

2023-01-10 19:38 UTC, aykevl commented on src/runtime/string.go
> +    s := unsafe.Slice(p, len(b))
This results in a compiler error. I think you need this:

```suggestion
    s := unsafe.Slice((*byte)(p), len(b))
```

2023-02-07 21:34 UTC, dgryski commented
Ping @aykevl

2023-11-24 04:11 UTC, anuraaga commented
@dgryski @aykevl I happened to need this, was wondering if this PR could be merged. Thanks

2023-11-24 05:05 UTC, dgryski commented
Odd we didn't merge this at the time. Looks like it just needs to be rebased.

2023-12-07 14:19 UTC, aykevl commented
@waj334 can you rebase this PR?

2024-09-19 10:12 UTC, leongross requested changes
PR #4470 which is a rebase of this PR was merged. Please consider closing this PR.

2024-09-19 11:23 UTC, deadprogram commented
Closing since it was superseded by #4470 as pointed out by @leongross 

Thank you again everyone!

2024-09-19 11:23 UTC, closed without merging