Gc precise heap
tinygo-org/tinygo pull request #3346
Opened 2022-12-18 23:03 UTC by aykevl

2022-12-18 23:16 UTC, aykevl commented
Looks like I need to update a few tests to get this to pass CI.

2022-12-18 23:23 UTC, dgryski commented
Exciting! I'll give this a review as soon as I can.

2022-12-20 14:16 UTC, aykevl commented
Rebased to fix the merge conflicts and to fix the interp test failure.

2022-12-20 14:43 UTC, aykevl commented on src/runtime/gc_blocks.go
> +		*(*[4]uintptr)(unsafe.Pointer(b.address())) = [4]uintptr{}
Oops, should have used `wordsPerBlock` instead of hardcoding the number 4.

2022-12-20 14:53 UTC, aykevl commented
Did a quick check to see whether other architectures are affected, and they (surprisingy) are: baremetal systems tend to have a decrease of around 16 bytes binary size and wasm tends to have an increase in binary size of 11 bytes. Probably as a result of some changes around inlining heuristics. Nothing to worry about, honestly.

Of course, where the precise GC is enabled there is a much bigger increase of 400+ bytes. This is expected, and should not be a problem at all for these systems.

2022-12-20 15:38 UTC, aykevl commented
Currently investigating what appears to be a memory corruption on arm.

2022-12-20 16:23 UTC, aykevl commented
Should be fixed now. The issue was that the `runtime.align` function did not correctly align objects: they should be aligned to an 8 byte boundary and not to a 4 byte boundary.

2023-01-05 05:11 UTC, dgryski requested changes
Pretty confident this is correct (it passes the corpus, which is always encouraging).  Just a bunch of questions.

2023-01-05 05:11 UTC, dgryski commented on src/internal/task/task_stack.go
> +	r := (*calleeSavedRegs)(unsafe.Add(stack, stackSize-unsafe.Sizeof(calleeSavedRegs{})))
Any other places in the runtime tree we should switch to using `unsafe.Add` ?

2023-01-05 05:11 UTC, dgryski commented on src/runtime/arch_arm.go
> +	return (ptr + 7) &^ 7
Did you check all the other `align` implementations to make sure they're correct?

2023-01-05 05:11 UTC, dgryski commented on src/runtime/gc_precise.go
> +		// Extract fields.
An example of what's happening here (vis a vis splitting the layout bits) might help here.

2023-01-05 05:11 UTC, dgryski commented on src/runtime/gc_precise.go
> +		if (*(*uint8)(unsafe.Add(scanner.bitmapAddr, index/8))>>(index%8))&1 == 0 {
Seems like a helper function might make this more readable, especially if we could change the type from `unsafe.Pointer` to `memoryBitmap` or something.

2023-01-05 05:11 UTC, dgryski commented on src/runtime/gc_precise.go
> +		scanner.size = 1
These seem like magic values we might want constants for?  I guess the rest of the pointer scanning logic just "works" with these both set to `1`.

2023-01-05 05:11 UTC, dgryski commented on src/runtime/gc_precise.go
> +	if scanner.index == scanner.size {
I know this is so that the `size = 1` stuff above works, but it seems to me we might like a different way handle this so that we can assert if 'nextIsPointer` is in fact called too many times and overflows the bitmap.

2023-01-05 05:11 UTC, dgryski commented on compiler/llvm.go
> +	reverseBytes(bitmapBytes) // big-endian to little-endian
Now that we're actually using the layout in the allocator, do we have any tests that it's correct?

2023-01-05 05:11 UTC, dgryski commented on src/runtime/gc_precise.go
> +func (scanner *gcObjectScanner) nextIsPointer(word, parent, addrOfWord uintptr) bool {
I wonder if this ends up being cleaner if we split this into `next()` call that advanced the index and `IsPointer` that does the check?

2023-01-05 05:11 UTC, dgryski commented on src/runtime/gc_blocks.go
> +			if !scanner.nextIsPointer(word, root.address(), addr) {
I feel like the fact we have the scanner and the word as two separate things here means they might get out of sync.  For example, `nextIsPointer`, but you're passing in `word`, so it should be `*this*IsPointer`, except that you need to increment the internal scanner index .... We should figure out the best API here.

2023-01-09 15:48 UTC, aykevl commented on src/internal/task/task_stack.go
> +	r := (*calleeSavedRegs)(unsafe.Add(stack, stackSize-unsafe.Sizeof(calleeSavedRegs{})))
Yes, lots of places. I have a local branch that I should finish and submit...

2023-01-11 20:53 UTC, aykevl reviewed
I've put a big comment at the top of gc_precise.go that should answer some questions you have. Please take another look.

2023-01-11 20:53 UTC, aykevl commented on src/internal/task/task_stack.go
> +	r := (*calleeSavedRegs)(unsafe.Add(stack, stackSize-unsafe.Sizeof(calleeSavedRegs{})))
I'll submit it after this branch (and perhaps #2640) have been merged, to avoid conflicts.

2023-01-11 20:53 UTC, aykevl commented on src/runtime/arch_arm.go
> +	return (ptr + 7) &^ 7
I should have. I've updated the PR and I think all `align` functions are now correct.

2023-01-11 20:53 UTC, aykevl commented on compiler/llvm.go
> +	reverseBytes(bitmapBytes) // big-endian to little-endian
There are some tests in compiler/testdata/gc.go, or do you mean something else?

2023-01-11 20:53 UTC, aykevl commented on src/runtime/gc_precise.go
> +	if scanner.index == scanner.size {
This is by design to support arrays. For example, if you do `make([]*byte, 10)` you'll create a datalayout of one word with size == 1 (on most architectures). The `size = 1` above merely uses this fact, it basically treats the object like it would `make([]*T, ...)` (that is, everything could be a pointer).

2023-01-11 20:53 UTC, aykevl commented on src/runtime/gc_precise.go
> +		scanner.size = 1
I have put a big comment explaining all of this at the top that should hopefully explain what happens here.

2023-01-11 20:53 UTC, aykevl commented on src/runtime/gc_blocks.go
> +			if !scanner.nextIsPointer(word, root.address(), addr) {
Yeah I was struggling with the API. Not too happy with what I have here but I couldn't figure out something better that is also generic. Suggestions for a better API are welcome :)

2023-01-11 21:10 UTC, dgryski approved these changes
One more question, but otherwise LGTM.

2023-01-11 21:10 UTC, dgryski commented on src/runtime/gc_precise.go
> +	if scanner.index == scanner.size {
So reading the comment about the `size`, I'm wondering if we know that for slices of structs the padding will always work out such that we'll never get "out-of-sync" with the layout bitmap.

2023-01-11 22:42 UTC, aykevl commented on src/runtime/gc_precise.go
> +	if scanner.index == scanner.size {
Well, it should. If it doesn't, that means there is a bug somewhere (which wouldn't be very surprising to me, this code hasn't been tested a lot). If you're interested, the relevant functions are `createObjectLayout` and `getPointerBitmap`.

2023-01-17 18:24 UTC, dgryski commented on src/runtime/gc_precise.go
> +	if scanner.index == scanner.size {
SGTM

2023-01-17 18:32 UTC, merged