`reflect`: Select constants and stubs
tinygo-org/tinygo pull request #3425
Opened 2023-02-02 03:23 UTC by bgould

Adds constants and stubs to `reflect` package to support compilation mentioned in https://github.com/tinygo-org/tinygo/issues/742#issuecomment-1411026796

2023-02-02 03:30 UTC, dgryski requested changes
These should probably be in `value.go` with everything else. I just put them in chan.go for convenience when I was trying to get the lua stuff to build.

2023-02-10 02:53 UTC, aykevl reviewed
> These should probably be in `value.go` with everything else.

Agreed, plus two really minor nits you can fix at the same time. Other than that, this looks good to me.

2023-02-10 02:53 UTC, aykevl commented on src/reflect/chan.go
> +
Nit: unnecessary newline

2023-02-10 02:53 UTC, aykevl commented on src/reflect/chan.go
> +
Same here.

2023-02-20 23:38 UTC, dgryski commented
Incorporated this change into https://github.com/tinygo-org/tinygo/pull/3470

2023-02-21 02:48 UTC, closed without merging