Add bluemicro840 board
tinygo-org/tinygo pull request #3749
Opened 2023-05-25 23:44 UTC by jpconstantineau

Takes care of the BlueMicro840 of issue #3746 

Schematic is located [here](https://nrf52.jpconstantineau.com/docs/bluemicro840_v1)
USB Vendor ID/Product ID were assigned for firmware on this device by [openmoko](https://github.com/openmoko/openmoko-usb-oui/blob/master/usb_product_ids.psv)

Tested on actual hardware.

2023-05-26 17:51 UTC, jpconstantineau commented
sizediff job fails with this error: Resource not accessible by integration

2023-05-29 20:49 UTC, deadprogram commented
> sizediff job fails with this error: Resource not accessible by integration

Please see https://github.com/tinygo-org/tinygo/pull/3757

2023-05-31 17:08 UTC, aykevl approved these changes
Looks good to me, with one small nit.

2023-05-31 17:08 UTC, aykevl commented on targets/bluemicro840.json
> +    "build-tags": ["bluemicro840"],
Perhaps you can also add the serial port?

```json
    "serial-port": ["1d50:6161"]
```

2023-05-31 17:11 UTC, aykevl requested changes
Actually, please also add a smoke test to the Makefile to make sure it continues to build without errors.

2023-06-01 17:27 UTC, aykevl commented on Makefile
> +	@$(MD5SUM) test.hex
One example should be good enough - feel free to pick any of the two.
(Each new board adds a second or so to CI time, and we have a lot of boards and a lot of PRs so I like to keep them to a minimum).

2023-06-01 19:04 UTC, aykevl approved these changes

2023-06-01 19:04 UTC, merged