GNUmakefile: add "help" target
tinygo-org/tinygo pull request #4390
Opened 2024-08-07 15:37 UTC by dkegel-fastly

Example output:

```
$ make help
clean                           Remove build directory
fmt                             Reformat source
fmt-check                       Warn if any source needs reformatting
gen-device                      Generate microcontroller-specific sources
llvm-source                     Get LLVM sources
llvm-build                      Build LLVM
lint                            Lint source tree
spell                           Spellcheck source tree
```

Might even work on windows, since git for windows comes with awk.

2024-08-07 18:54 UTC, archie2x approved these changes
Nice.

2024-08-08 12:52 UTC, leongross requested changes

2024-08-08 12:52 UTC, leongross commented on GNUmakefile
> +tinygo: ## Build the Go compiler
nit: Maybe make it 
```suggestion
tinygo: ## Build the TinyGo compiler
```
to make a distinction from big go?

2024-08-08 15:43 UTC, archie2x reviewed
Mention this in BUILDING.md ?

```patch
diff --git a/BUILDING.md b/BUILDING.md
index dfc069c0..c26650fd 100644
--- a/BUILDING.md
+++ b/BUILDING.md
@@ -28,6 +28,21 @@ build tools to be built. Go is of course necessary to build TinyGo itself.
 The rest of this guide assumes you're running Linux, but it should be equivalent
 on a different system like Mac.
 
+## Help
+
+The GNUmakefile has a 'help' target
+
+    % make help
+    clean                           Remove build directory
+    fmt                             Reformat source
+    fmt-check                       Warn if any source needs reformatting
+    gen-device                      Generate microcontroller-specific sources
+    llvm-source                     Get LLVM sources
+    llvm-build                      Build LLVM
+    tinygo                          Build the Go compiler
+    lint                            Lint source tree
+    spell                           Spellcheck source tree
+
 ## Download the source
 
 The first step is to download the TinyGo sources (use `--recursive` if you clone
```

2024-08-12 15:59 UTC, dkegel-fastly commented on GNUmakefile
> +tinygo: ## Build the Go compiler
Done

2024-08-12 15:59 UTC, dkegel-fastly commented
> Mention this in BUILDING.md ?

Done.

2024-08-12 16:44 UTC, ydnar approved these changes
LGTM. Thank you Dan!

2024-08-12 17:17 UTC, deadprogram commented
@dkegel-fastly do you want to squash these commits before merge? or do you want me to do so for you?

2024-08-12 17:19 UTC, merged

2024-08-12 17:19 UTC, dkegel-fastly commented
I'll squash and merge now that you're had a chance to look, thanks.