stub runtime_{Before,After}Exec for linkage
tinygo-org/tinygo pull request #4426
Opened 2024-08-21 15:54 UTC by archie2x

Fixes:
   
    u-root/cmds/core/init$ GOARCH={arm64,amd64} tinygo build -tags noasm
    /usr/lib/go-1.22/src/syscall/exec_unix.go:282: linker could not find symbol syscall.runtime_BeforeExec
    /usr/lib/go-1.22/src/syscall/exec_unix.go:308: linker could not find symbol syscall.runtime_AfterExec

I copied BigGo/src/runtime/proc.go for this, duplicating the `//go:linkname`

In BigGo, exec calls are serialized because of golang/go#19546 but uses a rwlock whose implementation would require a lot of file import from BigGo or a merge of tinygo/bigGo runtime against current policy. I may follow this up with a simple sync/Mutex.

2024-08-21 16:00 UTC, leongross commented
I think you are addressing an important issue here, that has not been taken care of atm.
I [tried](https://github.com/tinygo-org/tinygo/pull/4377/files#diff-7bfe0cde9452a92a322105e0dd7094e255f82098a6013672dd25747364916423) to implement sth similar bit quite did not get it working, although this would be a great benefit.

2024-08-23 21:33 UTC, archie2x commented
> I think you are addressing an important issue here, that has not been taken care of atm. I [tried](https://github.com/tinygo-org/tinygo/pull/4377/files#diff-7bfe0cde9452a92a322105e0dd7094e255f82098a6013672dd25747364916423) to implement sth similar bit quite did not get it working, although this would be a great benefit.

I saw your PR. I haven't pulled it / attempted to run it but I think it's missing these stubs for some reason? Does it work without them?

2024-08-27 12:00 UTC, leongross requested changes
I checked out your changes and built the failing cmdlet [switch_root](https://github.com/u-root/u-root/blob/main/cmds/core/switch_root/switch_root_linux.go) with it and this works just fine.

For context: The previous errors were:
```
ld.lld: error: undefined symbol: syscall.runtime_BeforeExec
>>> referenced by exec_unix.go:279 (/usr/lib/golang/src/syscall/exec_unix.go:279)
>>>               /tmp/tinygo131981138/main.lto.main.o:(runtime.run$1$gowrapper)

ld.lld: error: undefined symbol: syscall.runtime_AfterExec
>>> referenced by exec_unix.go:305 (/usr/lib/golang/src/syscall/exec_unix.go:305)
>>>               /tmp/tinygo131981138/main.lto.main.o:(runtime.run$1$gowrapper)
failed to run tool: ld.lld
error: failed to link /tmp/tinygo131981138/main: exit status 1
```

2024-08-27 12:00 UTC, leongross commented on src/runtime/proc.go
> +	// satisfy link.
Put this maybe before the function to generate the doc string?

2024-08-27 12:02 UTC, leongross approved these changes

2024-08-27 12:02 UTC, leongross commented on src/runtime/proc.go
> +// Copyright 2014 The Go Authors. All rights reserved.
nit:

```suggestion
// Copyright 2024 The Go Authors. All rights reserved.
```

2024-08-27 12:06 UTC, leongross commented
@aykevl @deadprogram

2024-08-27 15:37 UTC, leongross commented
On a kind of related note: https://github.com/tinygo-org/tinygo/pull/4384 implements the missing signals so the linker does not break the compilation

2024-09-04 21:18 UTC, deadprogram commented
Thank you for the PR @archie2x and to @leongross for review. Now merging.

2024-09-04 21:18 UTC, merged

2024-09-05 10:22 UTC, leongross commented
Thanks @deadprogram for merging.