wasip1: deduplicate target selection
tinygo-org/tinygo pull request #4437
Opened 2024-08-26 17:01 UTC by aykevl

Before this change, `GOOS=wasip1 GOARCH=wasm` and `-target=wasip1` were entirely separate configurations that just happened to be the same in practice. This change makes sure we keep only one of them to avoid inconsistencies.

This fixes the TODO here: https://github.com/tinygo-org/tinygo/pull/4175#issuecomment-1977326088

2024-08-26 17:23 UTC, dgryski commented
If we're deleting the wasip1 target json file, what is the proper fix for a custom target json that wants to inherit from that wasip1?  For example, https://github.com/fastly/compute-sdk-go/blob/main/targets/fastly-compute-wasip1.json

2024-08-26 19:39 UTC, ydnar commented
Would inheritance work for implied or config-less targets?

2024-08-27 12:15 UTC, aykevl commented
> If we're deleting the wasip1 target json file, what is the proper fix for a custom target json that wants to inherit from that wasip1?

Oh, that's a good point. Thanks for letting me know this is being done!

I could do it the other way round, and remove the built-in configuration? In that case, `GOOS=wasip1 GOARCH=wasm` would be special-cased to load targets/wasip1.json instead.

2024-08-27 12:18 UTC, deadprogram commented
>  In that case, GOOS=wasip1 GOARCH=wasm would be special-cased to load targets/wasip1.json instead.

That sounds more flexible to me, but I will let @dgryski weigh in first before any conclusive decision.

2024-08-27 14:20 UTC, ydnar commented
The JSON config files seem like the right path. Would this also apply to other GOOS/GOARCH pairs?

(I'd considered renaming wasip1.json to wasm-waspi1.json, so the target name was the implied double)

2024-08-27 14:50 UTC, dgryski commented
I agree telling the compiler to load a different `json` file does seem like a nicer fix.

2024-09-10 18:33 UTC, ydnar requested changes
My preference is to retain the `wasi.json` and `wasip1.json` configuration files, so they can be inherited from first-party and user-defined targets.

Perhaps worth having `GOOS=wasip1 GOARCH=wasm` load `wasip1.json`?

2024-10-21 14:36 UTC, ydnar commented
Do we want to close this in favor of keeping the target files as canonical?

2025-02-21 09:07 UTC, deadprogram commented
> Do we want to close this in favor of keeping the target files as canonical?

I think we should close it, yes. target files FTW! :smile:

2025-02-28 17:06 UTC, deadprogram commented
Now closing since #4746 answers this: the target file is authoritative source of build settings.

2025-02-28 17:06 UTC, closed without merging